export const CAR_CATALOG: Record<string, string[]> = {
  'Nissan': ['Versa', 'Sentra', 'March', 'Kicks', 'NP300 / Frontier', 'X-Trail', 'Altima', 'Tiida', 'Urvan', 'Pathfinder', 'Murano', 'Z / 370Z'],
  'Chevrolet': ['Aveo', 'Onix', 'Tracker', 'Captiva', 'Silverado / Cheyenne', 'S10', 'Colorado', 'Groove', 'Trax', 'Tornado', 'Cavalier', 'Suburban', 'Tahoe', 'Camaro'],
  'Volkswagen': ['Jetta', 'Vento', 'Gol', 'Polo', 'Virtus', 'Taos', 'Tiguan', 'Nivus', 'Saveiro', 'Golf', 'Teramont', 'Passat', 'Beetle', 'Amarok'],
  'Toyota': ['Corolla', 'Yaris', 'RAV4', 'Hilux', 'Tacoma', 'Camry', 'Prius', 'Avanza', 'Sienna', 'Highlander', 'Tundra', 'Corolla Cross', 'Land Cruiser'],
  'Ford': ['Mustang', 'F-150 / Lobo', 'Ranger', 'Escape', 'Explorer', 'Edge', 'Bronco / Bronco Sport', 'Maverick', 'Transit', 'Focus', 'Fiesta', 'EcoSport', 'Expedition'],
  'Kia': ['Rio', 'Forte', 'K3', 'Seltos', 'Sportage', 'Soul', 'Sorento', 'Carnival', 'Stinger', 'Niro', 'EV6'],
  'Honda': ['Civic', 'CR-V', 'City', 'HR-V', 'Accord', 'Fit', 'BR-V', 'Pilot', 'Odyssey', 'Ridgeline'],
  'Mazda': ['Mazda 2', 'Mazda 3', 'CX-3', 'CX-30', 'CX-5', 'CX-50', 'CX-90', 'Mazda 6', 'MX-5'],
  'Hyundai': ['Grand i10', 'Accent', 'Elantra', 'Creta', 'Tucson', 'Santa Fe', 'Palisade', 'Kona', 'Ioniq 5', 'HB20'],
  'MG': ['MG 5', 'ZS', 'GT', 'HS', 'RX8', 'MG 4', 'MG One', 'Cyberster'],
  'Seat': ['Ibiza', 'León', 'Arona', 'Ateca', 'Tarraco', 'Toledo'],
  'BMW': ['Serie 1', 'Serie 2', 'Serie 3', 'Serie 4', 'Serie 5', 'Serie 7', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'M2', 'M3', 'M4', 'M5', 'i4', 'iX'],
  'Mercedes-Benz': ['Clase A', 'Clase C', 'Clase E', 'Clase S', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'Clase G', 'Sprinter', 'AMG GT'],
  'Audi': ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'e-tron', 'TT', 'R8'],
  'Jeep': ['Wrangler', 'Grand Cherokee', 'Compass', 'Renegade', 'Gladiator', 'Cherokee'],
  'Renault': ['Kwid', 'Duster', 'Oroch', 'Koleos', 'Stepway', 'Sandero', 'Logan', 'Kangoo', 'Megane'],
  'Suzuki': ['Swift', 'Baleno', 'Jimny', 'Vitara', 'S-Cross', 'Ertiga', 'Ignis', 'Ciaz'],
  'BYD': ['Dolphin', 'Seal', 'Yuan Plus', 'Song Plus', 'Tang', 'Han', 'Shark'],
  'Cupra': ['Formentor', 'Leon', 'Ateca', 'Born', 'Tavascan'],
  'Chirey / Chery': ['Tiggo 2 Pro', 'Tiggo 4 Pro', 'Tiggo 7 Pro', 'Tiggo 8 Pro', 'Arrizo 8'],
  'Omoda': ['C5', 'O5', 'O5 GT'],
  'Subaru': ['Impreza', 'WRX', 'XV / Crosstrek', 'Forester', 'Outback', 'BRZ'],
  'Peugeot': ['208', '2008', '3008', '5008', 'Partner', 'Rifter', 'Expert'],
  'Mitsubishi': ['L200', 'Mirage G4', 'Outlander', 'Montero Sport', 'Eclipse Cross', 'Xpander'],
  'RAM / Dodge': ['RAM 700', 'RAM 1500', 'RAM 2500', 'Attitude', 'Challenger', 'Charger', 'Durango', 'Journey'],
  'GMC': ['Sierra', 'Yukon', 'Acadia', 'Terrain', 'Canyon'],
  'Volvo': ['XC40', 'XC60', 'XC90', 'C40', 'S60', 'EX30'],
  'Mini': ['Cooper', 'Countryman', 'Clubman'],
  'Tesla': ['Model 3', 'Model Y', 'Model S', 'Model X', 'Cybertruck'],
  'Lexus': ['IS', 'ES', 'UX', 'NX', 'RX', 'GX', 'LX'],
  'Porsche': ['911', 'Cayenne', 'Macan', 'Panamera', 'Taycan', '718 Cayman / Boxster']
};
